version: '3'

services:
    client.fllevent.com:
      build: ./client.fllevent.com
      restart: always
      ports:
        - 80:80
      networks:
        vpcbr:
          ipv4_address: 10.5.0.3
    api.fllevent.com:
      build: ./api.fllevent.com
      restart: always
      ports:
        - 4000:8000
      networks:
        vpcbr:
          ipv4_address: 10.5.0.4
    db:
      image: mysql
      restart: always
      environment:
                - MYSQL_DATABASE=${MYSQL_DATABASE}
                - MYSQL_USER=${MYSQL_USER}
                - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
            - ./db:/var/lib/mysql
      ports:
            - "3306:3306"
      networks:
        vpcbr:
          ipv4_address: 10.5.0.5
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ports:
        - "5000:80"
      networks:
        vpcbr:
          ipv4_address: 10.5.0.6
      links:
         # for mysql container
        - "db:db"
volumes:
    db:
      driver: "local"

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
        #  gateway: 10.5.0.1