version: '3.2'

services:
    # clientv2.fllevent.com:
    #   build: ./clientv2.fllevent.com
    #   hostname: clientv2
    #   restart: always
    #   ports:
    #     - 8081:80
    #   networks:
    #     vpcbr:
    #       ipv4_address: 10.5.0.2
    #   environment:
    #     VIRTUAL_HOST: clientv2.${HOST}
    #     VIRTUAL_PORT: "8081"
    client.fllevent.com:
      build: ./client.fllevent.com
      hostname: client
      restart: always
      ports:
        - 8080:80
      networks:
        vpcbr:
          ipv4_address: 10.5.0.3
      environment:
        VIRTUAL_HOST: ${HOST}
        VIRTUAL_PORT: "8080"
    api.fllevent.com:
      build: ./api.fllevent.com
      restart: always
      ports:
        - 4000:8000
      networks:
        vpcbr:
          ipv4_address: 10.5.0.4
      environment:
        VIRTUAL_HOST: api.${HOST}
        VIRTUAL_PORT: "4000"
    db:
      image: mysql
      restart: always
      environment:
                - MYSQL_DATABASE=${MYSQL_DATABASE}
                - MYSQL_USER=${MYSQL_USER}
                - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
            - ./db:/var/lib/mysql
      ports:
            - "3306:3306"
      networks:
        vpcbr:
          ipv4_address: 10.5.0.5
    phpmyadmin.fllevent.com:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - "8002:80"
      environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            VIRTUAL_HOST: phpmyadmin.${HOST}
            VIRTUAL_PORT: "8002"
      networks:
        vpcbr:
          ipv4_address: 10.5.0.11
      links:
         # for mysql container
        - "db:db"
volumes:
  db:
    driver: "local"

networks:
  vpcbr:
    external:
      name: flleventcom_vpcbr
